//! HTTP / WebSocket endpoints powering the **Cursor MCP "PChat-like" bridge**.
//!
//! The endpoint surface has two audiences:
//!
//! 1. **The bridge process** (`vibe-kanban-mcp --mode cursor-bridge`): a
//!    stdio MCP server that Cursor IDE spawns. It long-polls
//!    `POST /api/cursor-mcp/bridge/wait` to deliver a single
//!    `wait_for_user_input` tool call and block until the user types a reply
//!    in vibe-kanban. The reply (or a `TIMEOUT_RENEW` keep-alive sentinel)
//!    is returned to Cursor's Composer Agent.
//!
//! 2. **The vibe-kanban frontend**: subscribes to `GET .../stream/ws` for
//!    live conversation updates and pulls an initial snapshot from
//!    `GET .../state`. User replies use the existing
//!    `POST /api/sessions/:id/follow-up` endpoint, which routes here via
//!    [`super::sessions::follow_up`] when the session's executor is
//!    `CURSOR_MCP`.

use std::time::Duration;

use axum::{
    Json, Router,
    extract::{Path, Query, State, ws::Message},
    http::StatusCode,
    response::{IntoResponse, Json as ResponseJson},
    routing::{get, post},
};
use deployment::Deployment;
use serde::{Deserialize, Serialize};
use services::services::cursor_mcp::{
    CursorMcpPatch, CursorMcpSessionSnapshot, FORCE_RENEW_INTERVAL,
};
use ts_rs::TS;
use utils::response::ApiResponse;
use uuid::Uuid;

use crate::{
    DeploymentImpl,
    middleware::signed_ws::{MaybeSignedWebSocket, SignedWsUpgrade},
};

// --------------------------------------------------------------------------
// Bridge → backend (long-poll wait)
// --------------------------------------------------------------------------

/// Body the bridge sends with each `wait_for_user_input` invocation.
#[derive(Debug, Deserialize, Serialize, TS)]
#[ts(export)]
pub struct BridgeWaitRequest {
    pub session_id: Uuid,
    /// UUID generated by the bridge per tool invocation. Echoed in any
    /// future cancel call.
    pub request_id: String,
    /// Complete assistant message text (what Cursor's Agent wants to show
    /// the user as its current reply).
    pub message: String,
    #[serde(default)]
    pub prompt: Option<String>,
    #[serde(default)]
    pub title: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, TS)]
#[ts(export)]
pub struct BridgeWaitResponse {
    /// User reply text, or one of the sentinels:
    /// - `"TIMEOUT_RENEW"` (silently re-call wait)
    /// - `"__USER_DISMISSED_QUEUE__"` (user cancelled the prompt)
    pub text: String,
}

async fn bridge_wait(
    State(deployment): State<DeploymentImpl>,
    Json(body): Json<BridgeWaitRequest>,
) -> Result<ResponseJson<BridgeWaitResponse>, StatusCode> {
    let svc = deployment.cursor_mcp();
    let rx = svc
        .enqueue_wait(
            body.session_id,
            body.request_id.clone(),
            body.message,
            body.prompt,
            body.title,
        )
        .await;

    // Hard upper bound: a few seconds beyond the auto-renew interval so the
    // bridge always sees a response. The service's internal renew timer
    // fires at FORCE_RENEW_INTERVAL and resolves rx with `TIMEOUT_RENEW`
    // before this hits.
    let max_wait = FORCE_RENEW_INTERVAL + Duration::from_secs(60);

    match tokio::time::timeout(max_wait, rx).await {
        Ok(Ok(text)) => Ok(ResponseJson(BridgeWaitResponse { text })),
        Ok(Err(_)) => {
            // Sender dropped. Treat as "renew" so the bridge re-calls.
            Ok(ResponseJson(BridgeWaitResponse {
                text: services::services::cursor_mcp::TIMEOUT_RENEW.to_string(),
            }))
        }
        Err(_) => {
            // Should not happen, but degrade gracefully.
            tracing::warn!("cursor-mcp bridge_wait exceeded hard timeout");
            Ok(ResponseJson(BridgeWaitResponse {
                text: services::services::cursor_mcp::TIMEOUT_RENEW.to_string(),
            }))
        }
    }
}

// --------------------------------------------------------------------------
// Frontend → backend (REST snapshot + cancel + launch config)
// --------------------------------------------------------------------------

async fn get_state(
    State(deployment): State<DeploymentImpl>,
    Path(session_id): Path<Uuid>,
) -> ResponseJson<ApiResponse<CursorMcpSessionSnapshot>> {
    let snap = deployment.cursor_mcp().snapshot(session_id).await;
    ResponseJson(ApiResponse::success(snap))
}

#[derive(Debug, Deserialize)]
pub struct CancelWaitBody {
    pub request_id: String,
}

async fn cancel_wait(
    State(deployment): State<DeploymentImpl>,
    Path(session_id): Path<Uuid>,
    Json(body): Json<CancelWaitBody>,
) -> Result<ResponseJson<ApiResponse<bool>>, StatusCode> {
    let ok = deployment
        .cursor_mcp()
        .cancel_wait(session_id, &body.request_id)
        .await;
    Ok(ResponseJson(ApiResponse::success(ok)))
}

/// Frontend → backend "the user typed a follow-up". Mirrors
/// `POST /api/sessions/:id/follow-up` so callers can choose the simpler
/// shape if they don't have a full `CreateFollowUpAttempt`.
#[derive(Debug, Deserialize, Serialize, TS)]
#[ts(export)]
pub struct ResolveBody {
    pub text: String,
}

async fn resolve_with_user_reply(
    State(deployment): State<DeploymentImpl>,
    Path(session_id): Path<Uuid>,
    Json(body): Json<ResolveBody>,
) -> ResponseJson<ApiResponse<bool>> {
    let ok = deployment
        .cursor_mcp()
        .resolve_with_user_reply(session_id, body.text)
        .await;
    ResponseJson(ApiResponse::success(ok))
}

/// What the frontend "Copy MCP config" button should put on the clipboard.
/// Path/binary resolution is best-effort: in dev we point at `cargo run`;
/// in packaged Tauri builds the user can read `mcp_binary_path` from
/// `/api/info` and tweak the snippet.
#[derive(Debug, Serialize, TS)]
#[ts(export)]
pub struct LaunchConfig {
    /// The fully-formed JSON snippet to drop under
    /// `mcpServers.<name>` in `~/.cursor/mcp.json`.
    pub mcp_json_snippet: String,
    /// The auto-suggested entry name (unique per session).
    pub server_name: String,
    /// Best-effort absolute path to the bridge binary.
    pub binary_path: Option<String>,
    /// The vibe-kanban session UUID embedded in the snippet.
    pub session_id: Uuid,
}

async fn launch_config(
    State(_deployment): State<DeploymentImpl>,
    Path(session_id): Path<Uuid>,
) -> ResponseJson<ApiResponse<LaunchConfig>> {
    let server_name = format!("vibe-kanban-cursor-mcp-{}", short_id(session_id));
    let binary_path = std::env::var("VK_MCP_BINARY").ok().or_else(|| {
        std::env::current_exe()
            .ok()
            .map(|p| p.display().to_string())
    });

    let snippet = serde_json::json!({
        server_name.clone(): {
            "command": binary_path.clone().unwrap_or_else(|| "vibe-kanban-mcp".to_string()),
            "args": [
                "--mode",
                "cursor-bridge",
                "--session-id",
                session_id.to_string()
            ]
        }
    });

    ResponseJson(ApiResponse::success(LaunchConfig {
        mcp_json_snippet: serde_json::to_string_pretty(&snippet)
            .unwrap_or_else(|_| "{}".to_string()),
        server_name,
        binary_path,
        session_id,
    }))
}

fn short_id(id: Uuid) -> String {
    id.simple().to_string().chars().take(8).collect()
}

// --------------------------------------------------------------------------
// Frontend WebSocket: live patches per session
// --------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
pub struct SessionStreamQuery {
    pub session_id: Uuid,
}

async fn stream_session_ws(
    ws: SignedWsUpgrade,
    Query(query): Query<SessionStreamQuery>,
    State(deployment): State<DeploymentImpl>,
) -> impl IntoResponse {
    ws.on_upgrade(move |socket| async move {
        if let Err(e) = handle_session_ws(socket, deployment, query.session_id).await {
            tracing::warn!("cursor-mcp session WS closed: {}", e);
        }
    })
}

async fn handle_session_ws(
    mut socket: MaybeSignedWebSocket,
    deployment: DeploymentImpl,
    session_id: Uuid,
) -> anyhow::Result<()> {
    let svc = deployment.cursor_mcp();
    let (snapshot, mut rx) = svc.subscribe_session(session_id).await;

    let initial = CursorMcpPatch::Snapshot(snapshot);
    let initial_text = serde_json::to_string(&initial)?;
    socket.send(Message::Text(initial_text.into())).await?;

    loop {
        tokio::select! {
            patch = rx.recv() => {
                match patch {
                    Ok(p) => {
                        let text = serde_json::to_string(&p)?;
                        if socket.send(Message::Text(text.into())).await.is_err() {
                            break;
                        }
                    }
                    Err(tokio::sync::broadcast::error::RecvError::Closed) => break,
                    Err(tokio::sync::broadcast::error::RecvError::Lagged(_)) => {
                        // Resync.
                        let snap = svc.snapshot(session_id).await;
                        let text = serde_json::to_string(&CursorMcpPatch::Snapshot(snap))?;
                        if socket.send(Message::Text(text.into())).await.is_err() {
                            break;
                        }
                    }
                }
            }
            inbound = socket.recv() => {
                match inbound {
                    Ok(Some(Message::Close(_))) => break,
                    Ok(Some(_)) => {}
                    Ok(None) => break,
                    Err(_) => break,
                }
            }
        }
    }

    Ok(())
}

// --------------------------------------------------------------------------
// Router
// --------------------------------------------------------------------------

pub fn router() -> Router<DeploymentImpl> {
    Router::new()
        // Bridge endpoint — the only one called by the stdio MCP process.
        // No relay signature: the bridge runs locally and reaches the
        // backend directly via the port file.
        .route("/cursor-mcp/bridge/wait", post(bridge_wait))
        // Frontend session endpoints.
        .route("/cursor-mcp/sessions/{session_id}/state", get(get_state))
        .route(
            "/cursor-mcp/sessions/{session_id}/cancel",
            post(cancel_wait),
        )
        .route(
            "/cursor-mcp/sessions/{session_id}/resolve",
            post(resolve_with_user_reply),
        )
        .route(
            "/cursor-mcp/sessions/{session_id}/launch-config",
            get(launch_config),
        )
        // Live patches (frontend).
        .route("/cursor-mcp/sessions/stream/ws", get(stream_session_ws))
}
