[package]
name = "preview-proxy"
version = "0.1.45-permtest.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
ws-bridge = { path = "../ws-bridge" , version = "0.1.45-permtest.0" }
reqwest = { workspace = true }
http = "1"
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
utils = { path = "../utils" , version = "0.1.45-permtest.0" }
uuid = { version = "1.0", features = ["serde", "v4"] }
