[net]
# Enforce HTTPS for git dependencies
git-fetch-with-cli = true

[build]
# Enable incremental compilation for faster builds
incremental = true

[profile.release]
# Enable overflow checks in release mode for additional safety
overflow-checks = true

[registries.crates-io]
# Use the secure registry protocol
protocol = "sparse"

# Security-focused lints
[lints.rust]
unsafe_code = "warn"

[lints.clippy]
# Security and correctness lints
unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
todo = "warn"
unimplemented = "warn"
unreachable = "warn"

# Prevent common mistakes
indexing_slicing = "warn"
integer_arithmetic = "warn"

# Ensure good practices
missing_errors_doc = "warn"
missing_panics_doc = "warn"
must_use_candidate = "warn"