name: Setup Bun
description: Sets up Bun package manager with caching

inputs:
  bun-version:
    description: 'Bun version to use'
    required: false
    default: '1.1.45'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Get Bun cache directory
      id: bun-cache
      shell: bash
      run: echo "dir=$(bun pm cache)" >> $GITHUB_OUTPUT

    - name: Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.bun-cache.outputs.dir }}
          node_modules
          frontend/node_modules
          remote-frontend/node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-
